### ISSUE TITLE
Annotation library, tagsPartial search does not work

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#168]
When doing a tags_partial search in the annotation library the query string is populated but:

- the UI is not updated with a tag
- and the search results are not filtered

Initial DX indicates the network request is correctly sent to baw-server - may actually be a baw-server bug.

Reported  by Dez.

>Hi Anthony

>I am assuming once I am in the annotation library, if I type Noisy Miner in the tag box then hit filter then it will filter all the annotations to show just Noisy Miner. Well I tried this but it does not work, so what am I doing incorrectly.

 

>Regards

 

>Dezmond

**Comment by antmt** [comment]
https://github.com/QutBioacoustics/baw-client/tree/v0.12.0-hotfix1

Has been deployed to production.

This is a hotfix only. Problem needs to be dealt with in master as well.

Additionally an extra bug identified in addCalculatedProperties - `cannot read property id of undefined`. Due to library json sometimes returning objects with an empty projects array.

**Comment by antmt** [comment]
https://github.com/QutBioacoustics/baw-client/tree/v0.12.0-hotfix1

**Comment by atruskie** [comment]
Merged in: https://github.com/QutBioacoustics/baw-client/pull/177

Further patch in: ad1487047bed3a9089051cca129e562a19d938fd
